Python(PANDAS) Data Cleaning

In [2]:
import pandas as pd
import numpy as np

In [3]:
import os

print(os.getcwd())
print(os.listdir())

E:\Tata Group Stock Market Performance & Investment Analytics
['.ipynb_checkpoints', 'anaconda_projects', 'tata_group_stock_dataset.csv', 'Untitled.ipynb']

In [4]:
#load Dataset
df = pd.read_csv("tata_group_stock_dataset.csv")

In [6]:
#frist 5 rows
df.head()

,Date,Company Name,NSE Symbol,BSE Code,Sector,Open,High,Low,Close,Adjusted Close,Volume,Daily Return,MA_7,MA_30,Volatility_30D,"Market Cap (Current, INR Cr)",is_imputed
0,31-12-2024,Tata Consultancy Services,TCS,532540,IT Services,500.00,502.50,495.35,500.01,500.01,3098291,0.004580,505.36,512.68,0.285523,459674.8819,False
1,01-01-2025,Tata Consultancy Services,TCS,532540,IT Services,500.01,507.03,495.27,503.90,503.90,2382374,0.007780,507.20,512.33,0.287438,459674.8819,False
2,02-01-2025,Tata Consultancy Services,TCS,532540,IT Services,503.90,514.49,502.32,509.76,509.76,3634896,0.011629,509.04,511.98,0.289353,459674.8819,False
3,03-01-2025,Tata Consultancy Services,TCS,532540,IT Services,509.76,514.34,507.95,511.82,511.82,7026203,0.004041,510.88,511.63,0.291268,459674.8819,False
4,06-01-2025,Tata Consultancy Services,TCS,532540,IT Services,511.82,517.78,509.50,515.06,515.06,4906069,0.006330,512.72,511.28,0.293183,459674.8819,False

In [7]:
#Checking Dataset Structure
df.shape

(2394, 17)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2394 entries, 0 to 2393
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date                          2394 non-null   object
 1   Company Name                  2394 non-null   object
 2   NSE Symbol                    2394 non-null   object
 3   BSE Code                      2394 non-null   int64
 4   Sector                        2394 non-null   object
 5   Open                          2394 non-null   float64
 6   High                          2394 non-null   float64
 7   Low                           2394 non-null   float64
 8   Close                         2394 non-null   float64
 9   Adjusted Close                2394 non-null   float64
 10  Volume                        2394 non-null   int64
 11  Daily Return                  2390 non-null   float64
 12  MA_7                          2394 non-null   float64
 13  MA_30                         2394 non-null   float64
 14  Volatility_30D                2394 non-null   float64
 15  Market Cap (Current, INR Cr)  2394 non-null   float64
 16  is_imputed                    2394 non-null   bool
dtypes: bool(1), float64(10), int64(2), object(4)
memory usage: 301.7+ KB

In [9]:
#Checking Column Names
df.columns

Index(['Date', 'Company Name', 'NSE Symbol', 'BSE Code', 'Sector', 'Open',
       'High', 'Low', 'Close', 'Adjusted Close', 'Volume', 'Daily Return',
       'MA_7', 'MA_30', 'Volatility_30D', 'Market Cap (Current, INR Cr)',
       'is_imputed'],
      dtype='object')

In [10]:
#Checking Missing Values
df.isnull().sum()

Date                            0
Company Name                    0
NSE Symbol                      0
BSE Code                        0
Sector                          0
Open                            0
High                            0
Low                             0
Close                           0
Adjusted Close                  0
Volume                          0
Daily Return                    4
MA_7                            0
MA_30                           0
Volatility_30D                  0
Market Cap (Current, INR Cr)    0
is_imputed                      0
dtype: int64

In [11]:
#Checking Duplicate Rows 
df.duplicated().sum()

np.int64(0)

In [13]:
#Converting Data columns
df["Date"] = pd.to_datetime(df["Date"])

C:\Users\Anand Computers\AppData\Local\Temp\ipykernel_1284\3746763275.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Date"] = pd.to_datetime(df["Date"])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2394 entries, 0 to 2393
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date                          2394 non-null   datetime64[ns]
 1   Company Name                  2394 non-null   object
 2   NSE Symbol                    2394 non-null   object
 3   BSE Code                      2394 non-null   int64
 4   Sector                        2394 non-null   object
 5   Open                          2394 non-null   float64
 6   High                          2394 non-null   float64
 7   Low                           2394 non-null   float64
 8   Close                         2394 non-null   float64
 9   Adjusted Close                2394 non-null   float64
 10  Volume                        2394 non-null   int64
 11  Daily Return                  2390 non-null   float64
 12  MA_7                          2394 non-null   float64
 13  MA_30                         2394 non-null   float64
 14  Volatility_30D                2394 non-null   float64
 15  Market Cap (Current, INR Cr)  2394 non-null   float64
 16  is_imputed                    2394 non-null   bool
dtypes: bool(1), datetime64[ns](1), float64(10), int64(2), object(3)
memory usage: 301.7+ KB

In [16]:
#Data sorting 
df = df.sort_values(
    by=["Company Name", "Date"]).reset_index(drop=True)

In [17]:
#Checking Numerical Columns
df.describe()

,Date,BSE Code,Open,High,Low,Close,Adjusted Close,Volume,Daily Return,MA_7,MA_30,Volatility_30D,"Market Cap (Current, INR Cr)"
count,2394,2394.000000,2394.000000,2394.000000,2394.000000,2394.000000,2394.000000,2.394000e+03,2390.000000,2394.000000,2394.000000,2394.000000,2.394000e+03
mean,2025-10-05 04:45:06.766917120,513134.666667,571.182815,578.836048,564.180054,571.799799,571.799799,4.498101e+06,0.000907,571.657091,574.557558,0.311605,8.438303e+05
min,2024-12-31 00:00:00,500400.000000,261.200000,267.160000,259.060000,261.200000,261.200000,1.002200e+06,-0.087286,267.780000,266.090000,0.085144,2.141651e+05
25%,2025-05-19 00:00:00,500470.000000,476.950000,481.335000,469.815000,476.375000,476.375000,2.781248e+06,-0.012733,475.320000,474.413071,0.282286,4.596749e+05
50%,2025-10-06 00:00:00,500685.000000,552.130000,558.650000,544.430000,552.625000,552.625000,4.553900e+06,0.000937,551.650000,559.410000,0.313592,8.278747e+05
75%,2026-02-23 00:00:00,532540.000000,649.185000,657.422500,640.742500,649.705000,649.705000,6.202087e+06,0.013448,646.412500,639.360000,0.340287,1.315488e+06
max,2026-07-10 00:00:00,544028.000000,1218.340000,1229.440000,1205.590000,1218.340000,1218.340000,7.996396e+06,0.066987,1219.570000,1338.551429,0.509527,1.417904e+06
std,NaN,18094.040964,143.686438,146.032362,142.482760,144.837993,144.837993,2.000716e+06,0.019977,145.079681,150.486517,0.047847,4.399668e+05

In [18]:
#checking Missing data
df.isnull().sum()

Date                            0
Company Name                    0
NSE Symbol                      0
BSE Code                        0
Sector                          0
Open                            0
High                            0
Low                             0
Close                           0
Adjusted Close                  0
Volume                          0
Daily Return                    4
MA_7                            0
MA_30                           0
Volatility_30D                  0
Market Cap (Current, INR Cr)    0
is_imputed                      0
dtype: int64

In [19]:
#Checking Duplicates
df.duplicated().sum()

np.int64(0)

In [20]:
df.duplicated(subset=["Company Name", "Date"]).sum()

np.int64(0)

In [21]:
# Check if High price is lower than Open or Close
df[
    (df["High"] < df["Open"]) |
    (df["High"] < df["Close"])
]

Empty DataFrame
Columns: [Date, Company Name, NSE Symbol, BSE Code, Sector, Open, High, Low, Close, Adjusted Close, Volume, Daily Return, MA_7, MA_30, Volatility_30D, Market Cap (Current, INR Cr), is_imputed]
Index: []

In [22]:
#Creating Year, Month, and Quarter
df["Year"] = df["Date"].dt.year

df["Month"] = df["Date"].dt.month

df["Month_Name"] = df["Date"].dt.month_name()

df["Quarter"] = "Q" + df["Date"].dt.quarter.astype(str)

df["Year_Month"] = df["Date"].dt.to_period("M").astype(str)

In [23]:
#createing price change

df["Price_Change"] = df["Close"] - df["Open"]

df["Price_Change_Percent"] = (
    (df["Close"] - df["Open"]) / df["Open"]
) * 100

In [25]:
#Create daily price

df["Price_Range"] = df["High"] - df["Low"]

df["Price_Range_Percent"] = (
    (df["High"] - df["Low"]) / df["Open"]
) * 100

In [27]:
df["Trend_Signal"] = np.where(
    df["MA_7"] > df["MA_30"],
    "Bullish",
    np.where(
        df["MA_7"] < df["MA_30"],
        "Bearish",
        "Neutral"
    )
)

In [28]:
df.head()

,Date,Company Name,NSE Symbol,BSE Code,Sector,Open,High,Low,Close,Adjusted Close,...,Year,Month,Month_Name,Quarter,Year_Month,Price_Change,Price_Change_Percent,Price_Range,Price_Range_Percent,Trend_Signal
0,2024-12-31,Tata Consultancy Services,TCS,532540,IT Services,500.00,502.50,495.35,500.01,500.01,...,2024,12,December,Q4,2024-12,0.01,0.002000,7.15,1.430000,Bearish
1,2025-01-01,Tata Consultancy Services,TCS,532540,IT Services,500.01,507.03,495.27,503.90,503.90,...,2025,1,January,Q1,2025-01,3.89,0.777984,11.76,2.351953,Bearish
2,2025-01-02,Tata Consultancy Services,TCS,532540,IT Services,503.90,514.49,502.32,509.76,509.76,...,2025,1,January,Q1,2025-01,5.86,1.162929,12.17,2.415162,Bearish
3,2025-01-03,Tata Consultancy Services,TCS,532540,IT Services,509.76,514.34,507.95,511.82,511.82,...,2025,1,January,Q1,2025-01,2.06,0.404112,6.39,1.253531,Bearish
4,2025-01-06,Tata Consultancy Services,TCS,532540,IT Services,511.82,517.78,509.50,515.06,515.06,...,2025,1,January,Q1,2025-01,3.24,0.633035,8.28,1.617756,Bullish

In [29]:
df[[
    "Date",
    "Company Name",
    "Open",
    "Close",
    "Price_Change",
    "Price_Change_Percent",
    "Trend_Signal"
]].head()

,Date,Company Name,Open,Close,Price_Change,Price_Change_Percent,Trend_Signal
0,2024-12-31,Tata Consultancy Services,500.00,500.01,0.01,0.002000,Bearish
1,2025-01-01,Tata Consultancy Services,500.01,503.90,3.89,0.777984,Bearish
2,2025-01-02,Tata Consultancy Services,503.90,509.76,5.86,1.162929,Bearish
3,2025-01-03,Tata Consultancy Services,509.76,511.82,2.06,0.404112,Bearish
4,2025-01-06,Tata Consultancy Services,511.82,515.06,3.24,0.633035,Bullish

In [30]:
df

,Date,Company Name,NSE Symbol,BSE Code,Sector,Open,High,Low,Close,Adjusted Close,...,Year,Month,Month_Name,Quarter,Year_Month,Price_Change,Price_Change_Percent,Price_Range,Price_Range_Percent,Trend_Signal
0,2024-12-31,Tata Consultancy Services,TCS,532540,IT Services,500.00,502.50,495.35,500.01,500.01,...,2024,12,December,Q4,2024-12,0.01,0.002000,7.15,1.430000,Bearish
1,2025-01-01,Tata Consultancy Services,TCS,532540,IT Services,500.01,507.03,495.27,503.90,503.90,...,2025,1,January,Q1,2025-01,3.89,0.777984,11.76,2.351953,Bearish
2,2025-01-02,Tata Consultancy Services,TCS,532540,IT Services,503.90,514.49,502.32,509.76,509.76,...,2025,1,January,Q1,2025-01,5.86,1.162929,12.17,2.415162,Bearish
3,2025-01-03,Tata Consultancy Services,TCS,532540,IT Services,509.76,514.34,507.95,511.82,511.82,...,2025,1,January,Q1,2025-01,2.06,0.404112,6.39,1.253531,Bearish
4,2025-01-06,Tata Consultancy Services,TCS,532540,IT Services,511.82,517.78,509.50,515.06,515.06,...,2025,1,January,Q1,2025-01,3.24,0.633035,8.28,1.617756,Bullish
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2389,2026-07-06,Tata Technologies,TATATECH,544028,IT/ER&D,684.22,687.80,679.65,685.56,685.56,...,2026,7,July,Q3,2026-07,1.34,0.195843,8.15,1.191137,Bearish
2390,2026-07-07,Tata Technologies,TATATECH,544028,IT/ER&D,685.56,708.28,683.00,702.13,702.13,...,2026,7,July,Q3,2026-07,16.57,2.417002,25.28,3.687496,Bearish
2391,2026-07-08,Tata Technologies,TATATECH,544028,IT/ER&D,702.13,720.29,701.71,718.36,718.36,...,2026,7,July,Q3,2026-07,16.23,2.311538,18.58,2.646234,Bearish
2392,2026-07-09,Tata Technologies,TATATECH,544028,IT/ER&D,718.36,718.87,705.86,712.68,712.68,...,2026,7,July,Q3,2026-07,-5.68,-0.790690,13.01,1.811070,Bearish
2393,2026-07-10,Tata Technologies,TATATECH,544028,IT/ER&D,712.68,725.28,705.60,720.95,720.95,...,2026,7,July,Q3,2026-07,8.27,1.160409,19.68,2.761408,Bearish

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2394 entries, 0 to 2393
Data columns (total 27 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Date                          2394 non-null   datetime64[ns]
 1   Company Name                  2394 non-null   object
 2   NSE Symbol                    2394 non-null   object
 3   BSE Code                      2394 non-null   int64
 4   Sector                        2394 non-null   object
 5   Open                          2394 non-null   float64
 6   High                          2394 non-null   float64
 7   Low                           2394 non-null   float64
 8   Close                         2394 non-null   float64
 9   Adjusted Close                2394 non-null   float64
 10  Volume                        2394 non-null   int64
 11  Daily Return                  2390 non-null   float64
 12  MA_7                          2394 non-null   float64
 13  MA_30                         2394 non-null   float64
 14  Volatility_30D                2394 non-null   float64
 15  Market Cap (Current, INR Cr)  2394 non-null   float64
 16  is_imputed                    2394 non-null   bool
 17  Year                          2394 non-null   int32
 18  Month                         2394 non-null   int32
 19  Month_Name                    2394 non-null   object
 20  Quarter                       2394 non-null   object
 21  Year_Month                    2394 non-null   object
 22  Price_Change                  2394 non-null   float64
 23  Price_Change_Percent          2394 non-null   float64
 24  Price_Range                   2394 non-null   float64
 25  Price_Range_Percent           2394 non-null   float64
 26  Trend_Signal                  2394 non-null   object
dtypes: bool(1), datetime64[ns](1), float64(14), int32(2), int64(2), object(7)
memory usage: 470.0+ KB

In [32]:
df.shape

(2394, 27)

In [33]:
df.head()

,Date,Company Name,NSE Symbol,BSE Code,Sector,Open,High,Low,Close,Adjusted Close,...,Year,Month,Month_Name,Quarter,Year_Month,Price_Change,Price_Change_Percent,Price_Range,Price_Range_Percent,Trend_Signal
0,2024-12-31,Tata Consultancy Services,TCS,532540,IT Services,500.00,502.50,495.35,500.01,500.01,...,2024,12,December,Q4,2024-12,0.01,0.002000,7.15,1.430000,Bearish
1,2025-01-01,Tata Consultancy Services,TCS,532540,IT Services,500.01,507.03,495.27,503.90,503.90,...,2025,1,January,Q1,2025-01,3.89,0.777984,11.76,2.351953,Bearish
2,2025-01-02,Tata Consultancy Services,TCS,532540,IT Services,503.90,514.49,502.32,509.76,509.76,...,2025,1,January,Q1,2025-01,5.86,1.162929,12.17,2.415162,Bearish
3,2025-01-03,Tata Consultancy Services,TCS,532540,IT Services,509.76,514.34,507.95,511.82,511.82,...,2025,1,January,Q1,2025-01,2.06,0.404112,6.39,1.253531,Bearish
4,2025-01-06,Tata Consultancy Services,TCS,532540,IT Services,511.82,517.78,509.50,515.06,515.06,...,2025,1,January,Q1,2025-01,3.24,0.633035,8.28,1.617756,Bullish

In [34]:
df["Price_Change_Percent"] = df["Price_Change_Percent"].round(2)

df["Price_Range_Percent"] = df["Price_Range_Percent"].round(2)

In [35]:
df.to_csv(
    "tata_group_stock_cleaned.csv",
    index=False
)